// A small, balanced dataset for client-side training
export const trainingData = [
  { text: "Win a free iPhone now! Click here to claim your prize.", label: "spam" },
  { text: "Congratulations! You've been selected for a cash prize.", label: "spam" },
  { text: "URGENT: Your account has been compromised. Verify now.", label: "spam" },
  { text: "Hot singles in your area waiting to chat.", label: "spam" },
  { text: "Buy Viagra, Cialis cheap online. No prescription needed.", label: "spam" },
  { text: "You have won a lottery! Send details to claim.", label: "spam" },
  { text: "Limited time offer! Get 90% off on all items.", label: "spam" },
  { text: "Earn $5000 from home easily. Sign up today.", label: "spam" },
  { text: "Meeting reminder: Project discussion at 3 PM.", label: "ham" },
  { text: "Hey, can we catch up for coffee later?", label: "ham" },
  { text: "Please find the attached invoice for last month.", label: "ham" },
  { text: "Mom called, she wants you to call her back.", label: "ham" },
  { text: "The package has been delivered to your doorstep.", label: "ham" },
  { text: "Are you coming to the birthday party tonight?", label: "ham" },
  { text: "Project deadline has been extended to Friday.", label: "ham" },
  { text: "Can you send me the notes from the lecture?", label: "ham" },
  { text: "Exclusive deal just for you! Act fast.", label: "spam" },
  { text: "Your subscription is expiring. Renew now.", label: "spam" },
  { text: "Make money fast with this simple trick.", label: "spam" },
  { text: "Double your income in just one week.", label: "spam" },
  { text: "Hey, did you see the game last night?", label: "ham" },
  { text: "Let's schedule a zoom call for tomorrow.", label: "ham" },
  { text: "Don't forget to buy milk on your way home.", label: "ham" },
  { text: "Happy Birthday! Hope you have a great day.", label: "ham" },
  { text: "FREE FREE FREE! Call now!", label: "spam" },
  { text: "Low interest loans available. Apply now.", label: "spam" },
  { text: "I'll be late for the meeting, start without me.", label: "ham" },
  { text: "Thanks for your help yesterday.", label: "ham" },
  { text: "Verify your email address to continue.", label: "spam" },
  { text: "Your order #12345 has been shipped.", label: "ham" },
  { text: "Lose weight fast with this miracle pill.", label: "spam" },
  { text: "Let's go for a hike this weekend.", label: "ham" }
] as const;
